# https://github.com/Azure/container-scan#ignoring-vulnerabilities
general:
  vulnerabilities:
    - CVE-2018-18074
    - CVE-2022-40897
  bestPracticeViolations:
    - CIS-DI-0001
    - DKL-DI-0006
    - CIS-DI-0006
    - CIS-DI-0003 
