name: Docker Image CI

on:
  push:
    branches:
      - $default-branch
      - development
      - master
    tags:
      - '*.*.*-*'
  # Run tests for any PRs
  pull_request:
  schedule:
    - cron: '43 10 * * 4'

env:
  IMAGE_NAME: dockerscan

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          check_filenames: true
          check_hidden: true
  super-linter:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4.4.1
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  shiftleft:
    name: shiftleft
    runs-on: ubuntu-latest
    steps:
      - name: Perform ShiftLeft Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports
          # Scan auto-detects the languages in your project. To override uncomment the below variable and set the type
          # type: credscan,java
          # type: python
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports
  build:
    needs:
      - codespell
      - super-linter
      - shiftleft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run:  docker build . --file Dockerfile --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag ${IMAGE_NAME}
      - name: Test the Docker image
        run: |
          CONTAINER_OUTPUT="$(docker run --rm -t ${IMAGE_NAME} -h)"
          TEST_STRING="$(echo ${CONTAINER_OUTPUT} | head -1 | cut -d' ' -f2)"
          if ! [ "${TEST_STRING}" = "dockerscan" ]; then exit 1; fi
      - name: Scan image with Container Scan
        uses: Azure/container-scan@v0
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          image-name: ${{ env.IMAGE_NAME }}
          severity-threshold: HIGH
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
# click has security issues (CVE-2015-8768)
#      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
#        uses: anchore/scan-action@main
#        with:
#          image: ${{ env.IMAGE_NAME }}
#          acs-report-enable: true
      - name: Move reports
        run: mkdir -p sarif-reports && cp *results.sarif sarif-reports/
      - name: Upload Reports
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'sarif-reports'
